import type { SoundCategory, SoundOption } from './config';

type BaseSoundOption = Omit<SoundOption, 'colorToken'>;

export const LIBRARY_BASE_SOUNDS: BaseSoundOption[] = [
  {
    id: 'creepy-creepy-02',
    name: 'Creepy 02',
    path: '/sounds/creepy/creepy-02.mp3',
    animation: 'fast',
    category: 'creepy',
    type: 'sfx',
    mood: 'creepy',
    price: 90,
  },
  {
    id: 'creepy-creepy-03',
    name: 'Creepy 03',
    path: '/sounds/creepy/creepy-03.mp3',
    animation: 'slow',
    category: 'creepy',
    type: 'sfx',
    mood: 'creepy',
    price: 80,
  },
  {
    id: 'creepy-creepy-04',
    name: 'Creepy 04',
    path: '/sounds/creepy/creepy-04.mp3',
    animation: 'fast',
    category: 'creepy',
    type: 'sfx',
    mood: 'creepy',
    price: 40,
  },
  {
    id: 'creepy-creepy-05',
    name: 'Creepy 05',
    path: '/sounds/creepy/creepy-05.mp3',
    animation: 'slow',
    category: 'creepy',
    type: 'sfx',
    mood: 'creepy',
    price: 60,
  },
  {
    id: 'creepy-creepy-06',
    name: 'Creepy 06',
    path: '/sounds/creepy/creepy-06.mp3',
    animation: 'slow',
    category: 'creepy',
    type: 'sfx',
    mood: 'creepy',
    price: 80,
  },
  {
    id: 'creepy-creepy-07',
    name: 'Creepy 07',
    path: '/sounds/creepy/creepy-07.mp3',
    animation: 'fast',
    category: 'creepy',
    type: 'sfx',
    mood: 'creepy',
    price: 40,
  },
  {
    id: 'creepy-creepy-08',
    name: 'Creepy 08',
    path: '/sounds/creepy/creepy-08.mp3',
    animation: 'slow',
    category: 'creepy',
    type: 'sfx',
    mood: 'creepy',
    price: 80,
  },
  {
    id: 'creepy-creepy-09',
    name: 'Creepy 09',
    path: '/sounds/creepy/creepy-09.mp3',
    animation: 'fast',
    category: 'creepy',
    type: 'sfx',
    mood: 'creepy',
    price: 20,
  },
  {
    id: 'creepy-creepy-mus-10',
    name: 'Creepy Mus 10',
    path: '/sounds/creepy/creepy-mus-10.mp3',
    animation: 'fast',
    category: 'creepy',
    type: 'sfx',
    mood: 'creepy',
    price: 50,
  },
  {
    id: 'creepy-creepy-mus-11',
    name: 'Creepy Mus 11',
    path: '/sounds/creepy/creepy-mus-11.mp3',
    animation: 'fast',
    category: 'creepy',
    type: 'sfx',
    mood: 'creepy',
    price: 60,
  },
  {
    id: 'creepy-creepy-noises-01',
    name: 'Creepy Noises 01',
    path: '/sounds/creepy/creepy-noises-01.mp3',
    animation: 'slow',
    category: 'creepy',
    type: 'sfx',
    mood: 'creepy',
    price: 90,
  },
  {
    id: 'cyberpunk-freesound-community-simple-dubstep-plucks-87487',
    name: 'Simple Dubstep Plucks 2',
    path: '/sounds/cyberpunk/freesound_community-simple-dubstep-plucks-87487.mp3',
    animation: 'fast',
    category: 'other',
    type: 'music',
    mood: 'cyberpunk',
    price: 90,
  },
  {
    id: 'cyberpunk-hardstyle-best1-84430',
    name: 'Hardstyle Best1 84430',
    path: '/sounds/cyberpunk/hardstyle-best1-84430.mp3',
    animation: 'slow',
    category: 'other',
    type: 'music',
    mood: 'cyberpunk',
    price: 70,
  },
  {
    id: 'cyberpunk-simple-hardstyle-melody-105356',
    name: 'Simple Hardstyle Melody',
    path: '/sounds/cyberpunk/simple-hardstyle-melody-105356.mp3',
    animation: 'slow',
    category: 'other',
    type: 'music',
    mood: 'cyberpunk',
    price: 40,
  },
  {
    id: 'cyberpunk-trance-beat-with-deep-bassline-102755',
    name: 'Trance Beat Deep 2',
    path: '/sounds/cyberpunk/trance-beat-with-deep-bassline-102755.mp3',
    animation: 'slow',
    category: 'other',
    type: 'music',
    mood: 'cyberpunk',
    price: 60,
  },
  {
    id: 'drumloop-drumloop-01',
    name: 'Drumloop 01',
    path: '/sounds/drumloop/drumloop-01.mp3',
    animation: 'fast',
    category: 'drums',
    type: 'beat',
    mood: 'energetic',
    price: 70,
  },
  {
    id: 'drumloop-drumloop-02',
    name: 'Drumloop 02',
    path: '/sounds/drumloop/drumloop-02.mp3',
    animation: 'fast',
    category: 'drums',
    type: 'beat',
    mood: 'energetic',
    price: 20,
  },
  {
    id: 'drumloop-drumloop-03',
    name: 'Drumloop 03',
    path: '/sounds/drumloop/drumloop-03.mp3',
    animation: 'slow',
    category: 'drums',
    type: 'beat',
    mood: 'energetic',
    price: 30,
  },
  {
    id: 'drumloop-drumloop-04',
    name: 'Drumloop 04',
    path: '/sounds/drumloop/drumloop-04.mp3',
    animation: 'slow',
    category: 'drums',
    type: 'beat',
    mood: 'energetic',
    price: 20,
  },
  {
    id: 'drumloop-drumloop-05',
    name: 'Drumloop 05',
    path: '/sounds/drumloop/drumloop-05.mp3',
    animation: 'slow',
    category: 'drums',
    type: 'beat',
    mood: 'energetic',
    price: 50,
  },
  {
    id: 'drumloop-drumloop-06',
    name: 'Drumloop 06',
    path: '/sounds/drumloop/drumloop-06.mp3',
    animation: 'slow',
    category: 'drums',
    type: 'beat',
    mood: 'energetic',
    price: 40,
  },
  {
    id: 'drumloop-drumloop-07',
    name: 'Drumloop 07',
    path: '/sounds/drumloop/drumloop-07.mp3',
    animation: 'slow',
    category: 'drums',
    type: 'beat',
    mood: 'energetic',
    price: 50,
  },
  {
    id: 'drumloop-drumloop-08',
    name: 'Drumloop 08',
    path: '/sounds/drumloop/drumloop-08.mp3',
    animation: 'fast',
    category: 'drums',
    type: 'beat',
    mood: 'energetic',
    price: 70,
  },
  {
    id: 'drumloop-drumloop-09',
    name: 'Drumloop 09',
    path: '/sounds/drumloop/drumloop-09.mp3',
    animation: 'slow',
    category: 'drums',
    type: 'beat',
    mood: 'energetic',
    price: 50,
  },
  {
    id: 'drumloop-drumloop-10',
    name: 'Drumloop 10',
    path: '/sounds/drumloop/drumloop-10.mp3',
    animation: 'slow',
    category: 'drums',
    type: 'beat',
    mood: 'energetic',
    price: 80,
  },
  {
    id: 'fun-backgroundmusicforvideos-funny-comedy-cartoon-background-music-334875',
    name: 'Backgroundmusicforvideos',
    path: '/sounds/fun/backgroundmusicforvideos-funny-comedy-cartoon-background-music-334875.mp3',
    animation: 'slow',
    category: 'other',
    type: 'sfx',
    mood: 'happy',
    price: 20,
  },
  {
    id: 'fun-dominique-garnier-energic-rock-for-kids-30-seconds-430554',
    name: 'Dominique Garnier',
    path: '/sounds/fun/dominique_garnier-energic-rock-for-kids-30-seconds-430554.mp3',
    animation: 'slow',
    category: 'other',
    type: 'sfx',
    mood: 'happy',
    price: 90,
  },
  {
    id: 'fun-fart-sfx-peido1-325544',
    name: 'Fart Sfx Peido1 325544',
    path: '/sounds/fun/fart-sfx-peido1-325544.mp3',
    animation: 'slow',
    category: 'other',
    type: 'sfx',
    mood: 'happy',
    price: 30,
  },
  {
    id: 'fun-happinessinmusic-happy-hiccup-parade-background-funny-music-356489',
    name: 'Happinessinmusic Happy',
    path: '/sounds/fun/happinessinmusic-happy-hiccup-parade-background-funny-music-356489.mp3',
    animation: 'slow',
    category: 'other',
    type: 'sfx',
    mood: 'happy',
    price: 80,
  },
  {
    id: 'fun-happinessinmusic-music-346468',
    name: 'Happinessinmusic 2',
    path: '/sounds/fun/happinessinmusic-music-346468.mp3',
    animation: 'slow',
    category: 'other',
    type: 'sfx',
    mood: 'happy',
    price: 20,
  },
  {
    id: 'fun-soundore-children-free-music-437487',
    name: 'Soundore Children Free',
    path: '/sounds/fun/soundore-children-free-music-437487.mp3',
    animation: 'slow',
    category: 'other',
    type: 'sfx',
    mood: 'happy',
    price: 60,
  },
  {
    id: 'fun-u-dxlduo3m2g-panic-182769',
    name: 'U Dxlduo3m2g Panic',
    path: '/sounds/fun/u_dxlduo3m2g-panic-182769.mp3',
    animation: 'fast',
    category: 'other',
    type: 'sfx',
    mood: 'happy',
    price: 80,
  },
  {
    id: 'fun-voicebosch-hype-phrases-for-music-festivals-deep-hardstyle-vocals-190531',
    name: 'Voicebosch Hype Phrases',
    path: '/sounds/fun/voicebosch-hype-phrases-for-music-festivals-deep-hardstyle-vocals-190531.mp3',
    animation: 'fast',
    category: 'other',
    type: 'sfx',
    mood: 'happy',
    price: 40,
  },
  {
    id: 'fun-zec53-happy-joyful-positive-kid-loop-272761',
    name: 'Zec53 Happy Joyful',
    path: '/sounds/fun/zec53-happy-joyful-positive-kid-loop-272761.mp3',
    animation: 'fast',
    category: 'other',
    type: 'sfx',
    mood: 'happy',
    price: 80,
  },
  {
    id: 'loop (cyber)-alien-i-trust-squarewave-drive-by-alien-i-trust-125-bpm-269471',
    name: 'Alien I Trust Squarewave',
    path: '/sounds/loop (cyber)/alien_i_trust-squarewave-drive-by-alien-i-trust-125_bpm-269471.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 50,
  },
  {
    id: 'loop (cyber)-darren-hirst-lucky-dragon-449514',
    name: 'Darren Hirst Lucky',
    path: '/sounds/loop (cyber)/darren_hirst-lucky-dragon-449514.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 30,
  },
  {
    id: 'loop (cyber)-darren-hirst-trap-trance-427268',
    name: 'Darren Hirst Trap Trance',
    path: '/sounds/loop (cyber)/darren_hirst-trap-trance-427268.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 90,
  },
  {
    id: 'loop (cyber)-delon-boomkin-future-trap-music-intro-new-raid-422477',
    name: 'Delon Boomkin Future',
    path: '/sounds/loop (cyber)/delon_boomkin-future-trap-music-intro-new-raid-422477.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 50,
  },
  {
    id: 'loop (cyber)-delon-boomkin-house-music-intro-new-434567',
    name: 'Delon Boomkin House',
    path: '/sounds/loop (cyber)/delon_boomkin-house-music-intro-new-434567.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 60,
  },
  {
    id: 'loop (cyber)-freesound-community-303-to-303-43083',
    name: '303 To 303',
    path: '/sounds/loop (cyber)/freesound_community-303-to-303-43083.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 40,
  },
  {
    id: 'loop (cyber)-freesound-community-dragontrance--string-loop-1b-100418',
    name: 'Dragontrance String 1b 2',
    path: '/sounds/loop (cyber)/freesound_community-dragontrance__string-loop-1b-100418.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 70,
  },
  {
    id: 'loop (cyber)-freesound-community-electronic-glitter-68293',
    name: 'Electronic Glitter 2',
    path: '/sounds/loop (cyber)/freesound_community-electronic-glitter-68293.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 90,
  },
  {
    id: 'loop (cyber)-freesound-community-goatrance-xgsm-sample-105698',
    name: 'Goatrance Xgsm 2',
    path: '/sounds/loop (cyber)/freesound_community-goatrance-xgsm-sample-105698.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 90,
  },
  {
    id: 'loop (cyber)-freesound-community-hardstyle-atmos01-fmin-150bpm-94733',
    name: 'Hardstyle Atmos01 Fmin 3',
    path: '/sounds/loop (cyber)/freesound_community-hardstyle-atmos01_fmin_150bpm-94733.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 70,
  },
  {
    id: 'loop (cyber)-freesound-community-intro-stellar-32947',
    name: 'Intro Stellar 2',
    path: '/sounds/loop (cyber)/freesound_community-intro_stellar-32947.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 50,
  },
  {
    id: 'loop (cyber)-freesound-community-melodic-synth-edm-32250',
    name: 'Melodic Synth Edm 2',
    path: '/sounds/loop (cyber)/freesound_community-melodic-synth-edm-32250.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 60,
  },
  {
    id: 'loop (cyber)-freesound-community-stsh-133-cm-anlg-lead-arp-9doai-28132',
    name: 'Stsh 133 Cm Anlg Lead',
    path: '/sounds/loop (cyber)/freesound_community-stsh_133_cm_anlg_lead_arp_9doai-28132.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 50,
  },
  {
    id: 'loop (cyber)-freesound-community-synth-bass-2-95953',
    name: 'Synth Bass 2',
    path: '/sounds/loop (cyber)/freesound_community-synth-bass-2-95953.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 30,
  },
  {
    id: 'loop (cyber)-freesound-community-synth-lead-03-83396--1-',
    name: 'Synth Lead 03 1',
    path: '/sounds/loop (cyber)/freesound_community-synth-lead-03-83396 (1).mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 50,
  },
  {
    id: 'loop (cyber)-freesound-community-synth-lead-03-83396',
    name: 'Synth Lead 03',
    path: '/sounds/loop (cyber)/freesound_community-synth-lead-03-83396.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 40,
  },
  {
    id: 'loop (cyber)-freesound-community-trance-loop-81094',
    name: 'Trance 2',
    path: '/sounds/loop (cyber)/freesound_community-trance-loop-81094.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 60,
  },
  {
    id: 'loop (cyber)-freesound-community-trance-synth-loop-100820',
    name: 'Trance Synth 2',
    path: '/sounds/loop (cyber)/freesound_community-trance-synth-loop-100820.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 50,
  },
  {
    id: 'loop (cyber)-freesound-community-trap-rap-hiphop-vibe-loop-62637',
    name: 'Trap Rap Hiphop Vibe 2',
    path: '/sounds/loop (cyber)/freesound_community-trap-rap-hiphop-vibe-loop-62637.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 90,
  },
  {
    id: 'loop (cyber)-freesound-community-video-game-music-loop-27629',
    name: 'Video Game 2',
    path: '/sounds/loop (cyber)/freesound_community-video-game-music-loop-27629.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 30,
  },
  {
    id: 'loop (cyber)-grand-project-on-the-road-to-the-eighties-loop1-177567',
    name: 'Grand Project Road To 2',
    path: '/sounds/loop (cyber)/grand_project-on-the-road-to-the-eighties_loop1-177567.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 40,
  },
  {
    id: 'loop (cyber)-idoberg-bass-riff-am-106bpm-490941',
    name: 'Idb Bass Riff Am',
    path: '/sounds/loop (cyber)/idoberg-bass-riff-am-106bpm-490941.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 50,
  },
  {
    id: 'loop (cyber)-idoberg-calming-melody-loop-291840',
    name: 'Idb Calming Melody',
    path: '/sounds/loop (cyber)/idoberg-calming-melody-loop-291840.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 20,
  },
  {
    id: 'loop (cyber)-idoberg-cinematic-vocals-loop-288531',
    name: 'Idb Cinema Voc',
    path: '/sounds/loop (cyber)/idoberg-cinematic-vocals-loop-288531.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 40,
  },
  {
    id: 'loop (cyber)-idoberg-funky-slap-bass-riff-dm-106bpm-490939',
    name: 'Idb Funky Slap Bass',
    path: '/sounds/loop (cyber)/idoberg-funky-slap-bass-riff-dm-106bpm-490939.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 80,
  },
  {
    id: 'loop (cyber)-idoberg-melodic-techno-melody-loop-286128--1-',
    name: 'Idb Melodic Techno',
    path: '/sounds/loop (cyber)/idoberg-melodic-techno-melody-loop-286128 (1).mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 90,
  },
  {
    id: 'loop (cyber)-idoberg-melodic-techno-melody-loop-286128',
    name: 'Idb Melodic Techno 2',
    path: '/sounds/loop (cyber)/idoberg-melodic-techno-melody-loop-286128.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 20,
  },
  {
    id: 'loop (cyber)-idoberg-melodic-techno-melody-v2-248886',
    name: 'Idb Melodic Techno 3',
    path: '/sounds/loop (cyber)/idoberg-melodic-techno-melody-v2-248886.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 40,
  },
  {
    id: 'loop (cyber)-idoberg-synthwave-loop-v1-254569',
    name: 'Idb Synthwave V1 2',
    path: '/sounds/loop (cyber)/idoberg-synthwave-loop-v1-254569.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 40,
  },
  {
    id: 'loop (cyber)-mleckert82-bass-loop-154191',
    name: 'M82 Bass 2',
    path: '/sounds/loop (cyber)/mleckert82-bass-loop-154191.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 60,
  },
  {
    id: 'loop (cyber)-mleckert82-synth-pad-loop-88710',
    name: 'M82 Synth Pad',
    path: '/sounds/loop (cyber)/mleckert82-synth-pad-loop-88710.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 60,
  },
  {
    id: 'loop (cyber)-mleckert82-trance-beat-loop-m-janneman-163024',
    name: 'M82 Trance Beat 2',
    path: '/sounds/loop (cyber)/mleckert82-trance-beat-loop-m-janneman-163024.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 70,
  },
  {
    id: 'loop (cyber)-mleckert82-trance-loop-marie-louise-janneman-163048--1-',
    name: 'M82 Trance Mari 3',
    path: '/sounds/loop (cyber)/mleckert82-trance-loop-marie-louise-janneman-163048 (1).mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 80,
  },
  {
    id: 'loop (cyber)-mleckert82-trance-loop-marie-louise-janneman-163048',
    name: 'M82 Trance Mari 4',
    path: '/sounds/loop (cyber)/mleckert82-trance-loop-marie-louise-janneman-163048.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 60,
  },
  {
    id: 'loop (cyber)-mleckert82-violin-loop-154193',
    name: 'M82 Violin 2',
    path: '/sounds/loop (cyber)/mleckert82-violin-loop-154193.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 90,
  },
  {
    id: 'loop (cyber)-playsound-like-a-boss-136519',
    name: 'PLYS Like A Boss',
    path: '/sounds/loop (cyber)/playsound-like-a-boss-136519.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 60,
  },
  {
    id: 'loop (cyber)-soundreality-beat-of-time-128705',
    name: 'SRLTY Beat Of',
    path: '/sounds/loop (cyber)/soundreality-beat-of-time-128705.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 20,
  },
  {
    id: 'loop (cyber)-soundreality-hold-on-beat-408795',
    name: 'SRLTY Hold Beat 2',
    path: '/sounds/loop (cyber)/soundreality-hold-on-beat-408795.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 40,
  },
  {
    id: 'loop (cyber)-soundtracklegends-intro-trance-upbeat-469256',
    name: 'Soundtracklegends Intro',
    path: '/sounds/loop (cyber)/soundtracklegends-intro-trance-upbeat-469256.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 30,
  },
  {
    id: 'loop (cyber)-soundtracklegends-intro-trance-upbeat-two-469260',
    name: 'SNDLGS Intr 2',
    path: '/sounds/loop (cyber)/soundtracklegends-intro-trance-upbeat-two-469260.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 20,
  },
  {
    id: 'loop (cyber)-van-wiese-90er-techno-dark-synth-melo-149797',
    name: 'Van Wiese 90er Techno',
    path: '/sounds/loop (cyber)/van_wiese-90er-techno-dark-synth-melo-149797.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 50,
  },
  {
    id: 'loop (cyber)-white-records-byte-blast-8-bit-arcade-music-background-music-for-video-24-second-208776',
    name: 'WREC Byte Blast',
    path: '/sounds/loop (cyber)/white_records-byte-blast-8-bit-arcade-music-background-music-for-video-24-second-208776.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'cyberpunk',
    price: 60,
  },
  {
    id: 'rhythm-11325622-noise-drum-loop-134bpm-245852',
    name: 'Noise Drum 134bpm 2',
    path: '/sounds/rhythm/11325622-noise-drum-loop-134bpm-245852.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 50,
  },
  {
    id: 'rhythm-11325622-one-way-ticket-sequence-134bpm-275886',
    name: '1Way Ticket Sequenc 2',
    path: '/sounds/rhythm/11325622-one-way-ticket-sequence-134bpm-275886.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 20,
  },
  {
    id: 'rhythm-alien-i-trust-hi-hat-amp-clap-loop-by-alien-i-trust-240628',
    name: 'Alien I Trust Hi Hat Amp',
    path: '/sounds/rhythm/alien_i_trust-hi-hat-amp-clap-loop-by-alien-i-trust-240628.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 70,
  },
  {
    id: 'rhythm-csongimuzsikal-techno-loop-273137',
    name: 'Csongimuzsikal Techno',
    path: '/sounds/rhythm/csongimuzsikal-techno-loop-273137.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 20,
  },
  {
    id: 'rhythm-darren-hirst-we-will-rock-you-458627',
    name: 'Darren Hirst We Will',
    path: '/sounds/rhythm/darren_hirst-we-will-rock-you-458627.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 60,
  },
  {
    id: 'rhythm-dj-tomg360-hardstyle-l00p-305454',
    name: 'Tomg360 Hardstyle',
    path: '/sounds/rhythm/dj_tomg360-hardstyle-l00p-305454.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 20,
  },
  {
    id: 'rhythm-eco-art-edm-drum-loops-134bmp-b-major-375585',
    name: 'Eco Art Edm Drum Loops',
    path: '/sounds/rhythm/eco-art-edm-drum-loops-134bmp-b-major-375585.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 60,
  },
  {
    id: 'rhythm-freesound-community-cancer-beat-01-66429',
    name: 'Cancer Beat 01',
    path: '/sounds/rhythm/freesound_community-cancer-beat-01-66429.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 80,
  },
  {
    id: 'rhythm-freesound-community-drk-psy-koreab-stuff-28726',
    name: 'Drk Psy Koreab Stuff 2',
    path: '/sounds/rhythm/freesound_community-drk-psy-koreab-stuff-28726.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 80,
  },
  {
    id: 'rhythm-freesound-community-grinder-drum-loop-6697',
    name: 'Grinder Drum 6697',
    path: '/sounds/rhythm/freesound_community-grinder-drum-loop-6697.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 90,
  },
  {
    id: 'rhythm-freesound-community-hardstyle-atmos01-fmin-150bpm-94733',
    name: 'Hardstyle Atmos01 Fmin 4',
    path: '/sounds/rhythm/freesound_community-hardstyle-atmos01_fmin_150bpm-94733.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 40,
  },
  {
    id: 'rhythm-freesound-community-trap-drum-loop-80481',
    name: 'Trap Drum 2',
    path: '/sounds/rhythm/freesound_community-trap-drum-loop-80481.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 40,
  },
  {
    id: 'rhythm-freesound-community-trap-rap-loop-135-bpm-100650',
    name: 'Trap Rap 135 Bpm',
    path: '/sounds/rhythm/freesound_community-trap-rap-loop-135-bpm-100650.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 80,
  },
  {
    id: 'rhythm-fronbondi-skegs-drum-addictive-percussive-rhythm-loop-01-120bpm-8bars-438642',
    name: 'Fronbondi Skegs Drum',
    path: '/sounds/rhythm/fronbondi_skegs-drum-addictive-percussive-rhythm-loop-01-120bpm-8bars-438642.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 80,
  },
  {
    id: 'rhythm-ghirawallace-ritmo-loop-bunciac-313953',
    name: 'Ghirawallace Ritmo 2',
    path: '/sounds/rhythm/ghirawallace-ritmo-loop-bunciac-313953.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 30,
  },
  {
    id: 'rhythm-idoberg-deep-house-drums-loop-312200',
    name: 'Idb Deep House Drums',
    path: '/sounds/rhythm/idoberg-deep-house-drums-loop-312200.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 20,
  },
  {
    id: 'rhythm-idoberg-groovy-bongos-loop-02-317904',
    name: 'Idb Groovy Bongos 02',
    path: '/sounds/rhythm/idoberg-groovy-bongos-loop-02-317904.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 60,
  },
  {
    id: 'rhythm-idoberg-melodic-techno-loop-408268',
    name: 'Idb Melodic Techno 4',
    path: '/sounds/rhythm/idoberg-melodic-techno-loop-408268.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 20,
  },
  {
    id: 'rhythm-kamhunt-trap-drumloop-154bpm-138004',
    name: 'Kamhunt Trap Drumloop',
    path: '/sounds/rhythm/kamhunt-trap-drumloop-154bpm-138004.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 80,
  },
  {
    id: 'rhythm-kamhunt-trap-king-2-drum-loop-140bpm-142225',
    name: 'Kamhunt Trap King 2 Drum',
    path: '/sounds/rhythm/kamhunt-trap-king-2-drum-loop-140bpm-142225.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 60,
  },
  {
    id: 'rhythm-kamhunt-trap-king-drum-loop-140bpm-142221',
    name: 'Kamhunt Trap King Drum',
    path: '/sounds/rhythm/kamhunt-trap-king-drum-loop-140bpm-142221.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 80,
  },
  {
    id: 'rhythm-kamhunt-typical-trap-loop-140bpm-129880',
    name: 'Kamhunt Typical Trap',
    path: '/sounds/rhythm/kamhunt-typical-trap-loop-140bpm-129880.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 90,
  },
  {
    id: 'rhythm-kamhunt-typical-trap-loop-2b-130751',
    name: 'Kamhunt Typical Trap 2 2',
    path: '/sounds/rhythm/kamhunt-typical-trap-loop-2b-130751.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 70,
  },
  {
    id: 'rhythm-liecio-t8-drum-loop-132283',
    name: 'Liecio T8 Drum 2',
    path: '/sounds/rhythm/liecio-t8-drum-loop-132283.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 80,
  },
  {
    id: 'rhythm-mleckert82-beat-loop-by-marie-louise-janneman-21287',
    name: 'M82 Beat Marie 2',
    path: '/sounds/rhythm/mleckert82-beat-loop-by-marie-louise-janneman-21287.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 20,
  },
  {
    id: 'rhythm-mleckert82-trap-beat-loop-by-marie-louise-janneman-21310',
    name: 'M82 Trap Beat',
    path: '/sounds/rhythm/mleckert82-trap-beat-loop-by-marie-louise-janneman-21310.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 30,
  },
  {
    id: 'rhythm-prod-by-stu-amped-808-trap-loop-145bpm-411111',
    name: 'Prod Stu Amped 808 Trap',
    path: '/sounds/rhythm/prod_by_stu-amped-808-trap-loop-145bpm-411111.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 30,
  },
  {
    id: 'rhythm-soundreality-drums-loop-75bpm-2-455451',
    name: 'SRLTY Drums 75b 2',
    path: '/sounds/rhythm/soundreality-drums-loop-75bpm-2-455451.mp3',
    animation: 'fast',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 30,
  },
  {
    id: 'rhythm-van-wiese-fertige-acid-melodie-zum-verwenden-149177',
    name: 'Van Wiese Fertige Acid',
    path: '/sounds/rhythm/van_wiese-fertige-acid-melodie-zum-verwenden-149177.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 90,
  },
  {
    id: 'rhythm-xcartmi-gener808-1-10802',
    name: 'Xcartmi Gener808 1 10802',
    path: '/sounds/rhythm/xcartmi-gener808-1-10802.mp3',
    animation: 'slow',
    category: 'beats',
    type: 'beat',
    mood: 'energetic',
    price: 90,
  },
  {
    id: 'tune-adinkra-audio-flute-melody-280554',
    name: 'Adinkra Flute Melody 2',
    path: '/sounds/tune/adinkra_audio-flute-melody-280554.mp3',
    animation: 'slow',
    category: 'melody',
    type: 'music',
    mood: 'happy',
    price: 50,
  },
  {
    id: 'tune-freesound-community-freesound-dance-104718',
    name: 'Dance 2',
    path: '/sounds/tune/freesound_community-freesound-dance-104718.mp3',
    animation: 'slow',
    category: 'melody',
    type: 'music',
    mood: 'happy',
    price: 90,
  },
  {
    id: 'tune-freesound-community-glockenspiel-melody-140bpm-28185',
    name: 'Glockenspiel Melody 2',
    path: '/sounds/tune/freesound_community-glockenspiel-melody-140bpm-28185.mp3',
    animation: 'slow',
    category: 'melody',
    type: 'music',
    mood: 'happy',
    price: 70,
  },
  {
    id: 'tune-freesound-community-trap-tone-30688',
    name: 'Trap Tone 2',
    path: '/sounds/tune/freesound_community-trap-tone-30688.mp3',
    animation: 'slow',
    category: 'melody',
    type: 'music',
    mood: 'happy',
    price: 40,
  },
  {
    id: 'tune-idoberg-edm-melody-loop-v3-264572',
    name: 'Idb Edm Melody V3 2',
    path: '/sounds/tune/idoberg-edm-melody-loop-v3-264572.mp3',
    animation: 'slow',
    category: 'melody',
    type: 'music',
    mood: 'happy',
    price: 50,
  },
  {
    id: 'tune-idoberg-nostalgia-melody-loop-v1-264546',
    name: 'Idb Nostalgia Melody',
    path: '/sounds/tune/idoberg-nostalgia-melody-loop-v1-264546.mp3',
    animation: 'slow',
    category: 'melody',
    type: 'music',
    mood: 'happy',
    price: 60,
  },
  {
    id: 'tune-ksyburt-cosmic-melody-434980',
    name: 'Ksyburt Cosmic Melody',
    path: '/sounds/tune/ksyburt-cosmic-melody-434980.mp3',
    animation: 'fast',
    category: 'melody',
    type: 'music',
    mood: 'happy',
    price: 20,
  },
  {
    id: 'tune-van-wiese-requiem-for-a-dream-synth-loop-melodie-111506',
    name: 'Van Wiese Requiem A 2',
    path: '/sounds/tune/van_wiese-requiem-for-a-dream-synth-loop-melodie-111506.mp3',
    animation: 'slow',
    category: 'melody',
    type: 'music',
    mood: 'happy',
    price: 70,
  },
];

// Folder-backed themes that were added to public/sounds after the original catalog.
// Keep these paths explicit so they remain available in the picker and deploy reliably.
export const PUBLIC_FOLDER_SOUNDS: BaseSoundOption[] = [
  ['acapella', 'flowers-on-the-moon-acapella-SBA-348956701-preview.mp3'],
  ['electronic', 'ah-ha-uk-SBA-300554938-preview.mp3'],
  ['japan', '泣きたい;_;.mp3'],
  ['lounge', 'the_mountain-stylish-stylish-muisc-508037.mp3'],
].map(([folder, file], index) => ({
  id: `folder-${folder}-${index}`,
  name: file.replace(/\.[^.]+$/, '').replace(/[-_]+/g, ' '),
  path: `/sounds/${folder === 'japan' ? 'kawaii' : folder}/${encodeURIComponent(file)}`,
  animation: 'slow',
  category: folder as SoundCategory,
  type: 'music',
  mood: 'other',
  price: 20,
}));
